# Publish web app to github pages
name: Publish

on:
  push:
    branches: [master, main]

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      #- run: npm test
      - run: npm run build
      - name: Deploy app to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true
          clean: true
      - run: npm run build:library
      #- name: Publish package on NPM
      #  run: npm publish --access public
